### ISSUE TITLE
Use formatting tool called Black - a standard python code formatter

### ISSUE THREAD

**Issue by Basanta78** [leapfrogtechnology/datamegh#3]
### Current Behaviour
Standard formatting tool and linting tool has not been used in the repo to maintain the standard of the code. A common tool should be introduced in order to maintain a common coding standard.

### Proposal

- Add pre-commit hook to auto-format the changed files

- Add a black checker in Travis CI to ensure the files are black formatted or not ( CI will exit with an error if the files are not formatted with black incase the developer pushes by ignoring the pre-commit hook)

**Note**: The whole repo will be strictly black formatted code.

**Comment by kabirbaidhya** [comment]
Awesome. Thanks for adding this @Basanta78.

cc @shakyapranin

**Comment by sbimochan** [comment]
-n would skip the hook 😅

**Comment by Basanta78** [comment]
Yes, -n will skip the hook. That's why we will be placing a black formatter checker in our CI which will error out with formatting error if the code has not been formatted with black and will stop the build. So, we will be strictly checking the standard of the code with the use of black.

**Comment by sbimochan** [comment]
That’s great to integrate in CI too.

**Comment by kabirbaidhya** [comment]
I agree - CI should fail if the code doesn't agree to our formatter.
